config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :statuses
  get 'home', to: 'statuses#index', as: :home
  root 'statuses#index'

  resources :contacts

  get '/:id', to: 'profiles#show'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	attr_accessible :content, :user_id
	belongs_to :user

	validates :content, presence: true,
						length: { minimum: 2 }

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :profile_name

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                            format: { with: /\A[a-zA-Z0-9_-]+\z/, message: "Please format correctly" }

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  def full_name
  	first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :first_name, :last_name, :profile_name, :email, :password, :password_confirmation
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user 
  		@statuses = @user.statuses.load
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
			when :alert
				"alert-error"
			when :notice
				"alert-success"
			else
				""
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home For Grandma</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <div class="navbar navbar-fixed-top global-nav">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">Home For Grandma</a>
			<ul class="nav">
				<li><%= link_to "Home Page", home_path %></li> 
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
					<li><%= link_to "Sign Out", logout_path %></li>
				<% else %>
					<li><%= link_to "Sigh Up", register_path %></li>
					<li><%= link_to "Sign In", login_path %></li>				
				<% end %>
			</ul>
		</div>
	</div>
</div> -->

<div class="header">
	<div class="container">
		<div class="row">
			<div class="span5">
				<div id="logo-img"></div>
				<div>
					<h1 id="logo">HomeForGrandma</h1>
				</div>
			</div>
			<div class="span5 offset1">
				<div class="content-container">
					<div class="logo-content1"></div>
					<div class="logo-content2"></div>
				</div>
			</div>	
		</div>

		<div class="row">
			<div class="span1"></div>
			<div id="video" class="span10">
				<div id="video_top"></div>
				<div id="video_main" style="width:100%;">
					<div class="fluid-width-video-wrapper">
						<iframe id="video_clip" frameborder="0" allowfullscreen="" mozallowfullscreen="" webkitallowfullscreen="" src="//www.youtube.com/embed/9A2nhjijhPs?autoplay=0&autohide=1&fs=1&rel=0&hd=1&wmode=opaque&enablejsapi=1">
						</iframe>
					</div>
				</div>
				<div id="video_bot"></div>
			</div>
			<div class="span1" style="padding-top:30px;margin-bottom:40px;margin-left:30px;">
				<a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out HomeForGrandma! It's 90 seconds to find senior living!" data-via="homeforgrandma" data-size="large" data-dnt="true">Tweet</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
				</script>
				<a href="//www.pinterest.com/pin/create/button/?url=http%3A%2F%2Fhomeforgrandma.com&media=https%3A%2F%2Ffarm4.staticflickr.com%2F3720%2F13568102535_b13df5b923.jpg&description=HomeForGrandma%3A%20Bringing%20new%20ideas%20to%20senior%20living" data-pin-do="buttonPin" data-pin-config="beside" data-pin-height="28"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_28.png" /></a>
				<!-- Please call pinit.js only once per page -->
				<script type="text/javascript" async src="//assets.pinterest.com/js/pinit.js"></script>
			</div>
			<div class="row">
			</div>
<!-- 			<div class="row">
				<div class="span8 offset2">
					<div class="should-we">Inform me when the website is live.</div>
					<div id="mc_signup">
						<form id="mc_signup_form" action="#mc_signup" method="post">
							<div class="mc_form_inside">
								<div id="mc_message" class="updated"> </div>
								<div class="mc_merge_var">
									<input type="text" class="mc_input" id="mc_mv_EMAIL" name="mc_mv_EMAIL" value="" size="18" placeholder="Email Address">
								</div>
								<div class="mc_signup_submit">
									<input id="mc_signup_submit" class="button" type="submit" value="Send Request!" name="mc_signup_submit">
								</div>
							</div>
						</form>
					</div>
				</div>
			</div> -->
		</div>
	</div>

<!-- 	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
		</div>
	<% end %>
	<% if flash[:notice] %>

	<% end %> -->


	
</div>

<div id="slider">
	<div id="slider_container" class="container">
		<div class="slides_container" style="overflow: hidden; position: relative; display: block;">
			<div class="slides_control" style="position: relative; width: 3600px; height: 120px; left: -1200px;">
				<div class="row" style="margin-top: 25px; position: absolute; top: 0px; left: 1200px; z-index: 0; opacity: 1;">
					<div class="span10 offset1">
						<div class="span3" style="margin-left:0px;"><h1>Contact Us</h1></div>
                        <div class="span6" style="margin-top:5px;">
                        	<span class="m700">info@homeforgrandma.com</span>
                            <br>
                            <p>(626)451-0023</p>
                        </div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
    <h1><%= @user.full_name %></h1>
</div>


<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  
</div>
<% if false %>
  <%= link_to 'List Your Property', new_status_path, class: "btn btn-success" %>

  <% @statuses.each do |status| %>
    <div class="status">
      <div class="row">
        <div class="span1">
          <%= image_tag status.user.gravatar_url %>
        </div>
        <div class="span7">
          <strong><%= status.user.full_name %></strong>
          <p><%= status.content %></p>
          <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
            <span class="admin">
              <%= link_to 'Edit', edit_status_path(status) %>
              <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %> 
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>